---



    - name:                            "BOM: Create checksums"
      block:
        - name:                        "BOM: Verify Files"
          ansible.builtin.stat:
            path:                      "{{ result.dest }}"
            checksum_algorithm:        sha256
          register:                    fs_check

        - name:                        "BOM: Show"
          ansible.builtin.debug:
            var:                       fs_check
            verbosity:                 2
          when:                        create_checksums is defined

        - name:                        "BOM: Line"
          ansible.builtin.blockinfile:
            path:                      "{{ bom_file }}"
            regexp:                    '      archive:      {{ item.archive }}'
            insertafter:               '      archive:      {{ item.archive }}'
            block:                     "      checksum:     {{ fs_check.stat.checksum }}"
            marker:                    "# {mark} ANSIBLE MANAGED BLOCK {{ item.archive }}"
          when:
            - fs_check is defined
            - create_checksums is defined
            - bom_file is defined

        - name:                        "BOM: Remove marker"
          ansible.builtin.lineinfile:
            path:                      "{{ bom_file }}"
            regexp:                    '# BEGIN ANSIBLE MANAGED BLOCK {{ item.archive }}'
            state:                      absent

        - name:                        "BOM: Remove marker"
          ansible.builtin.lineinfile:
            path:                      "{{ bom_file }}"
            regexp:                    '# END ANSIBLE MANAGED BLOCK {{ item.archive }}'
            state:                     absent
      when:
        - item.checksum is not defined
        - create_checksums is defined

    #   03) Upload files to Azure
    - name:                            "BOM: {{ bom_name }} Upload File {{ item.archive }}"

      ansible.builtin.command: >-
                                       az storage blob upload
                                         --account-name {{ account }}
                                         --account-key {{ sapbits_access_key }}
                                         --container-name {{ container }}
                                         --name {{ item.archive }}
                                         --file {{ result.dest }}
                                         --if-none-match "*"
                                         --no-progress
      delegate_to:                     localhost
      register:                        azresult
      ignore_errors:                   true
      failed_when:
        - azresult.rc != 0
        - azresult.stderr is defined
        - azresult.stderr.find("BlobAlreadyExists") == -1

    - name:                            "BOM: {{ bom_name }} Remove File {{ item.archive }}"
      become:                          true
      ansible.builtin.file:
        dest:                          "{{ download_directory }}/files/{{ item.archive }}"
        state:                         absent

  when: proceed

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
