# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                          Role to download the binaries                     |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---
# -------------------------------------+---------------------------------------8
#
# Description:  Create BOM download directories".
#

- name:                                "BOM: Create BOM download directories"
  ansible.builtin.file:
    path:                              "{{ item.path }}"
    state:                             directory
    mode:                              0755
  become:                              true
  become_user:                         root
  loop:
    - path: "{{ download_directory }}"
    - path: "{{ download_directory }}/tmp"
    - path: "{{ download_directory }}/bom"
    - path: "{{ download_directory }}/files"

# -------------------------------------+---------------------------------------8
#
- name:                                "BOM: Download File {{ item.archive }}"
  block:
    - name:                            "BOM: {{ bom_name }} Download File {{ item.archive }}"
      ansible.builtin.get_url:
        url:                           "{{ item.url  | trim }}"
        dest:                          "{{ download_directory }}/files/{{ item.archive }}"
        tmp_dest:                      "{{ download_directory }}/tmp"
        url_username:                  "{{ s_user }}"
        url_password:                  "{{ s_password }}"
        force_basic_auth:              true
        http_agent:                    'SAP Software Download'

      become:                          true
      become_user:                     root
      register:                        result
      until:                           result is succeeded or not result.changed
      retries:                         2
      delay:                           1
      no_log:                          false

    - name:                            "BOM: {{ bom_name }} Download File {{ item.archive }}"
      ansible.builtin.debug:
        var:                           result
        verbosity:                     2


# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/

...
