---
# https://blogs.sap.com/2019/12/04/sap-hana-hardware-and-cloud-measurement-tools-hcmt-replacement-of-hwcct-tool/

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ target_media_location }}"
    state: directory
    mode: '0755'
    
- name: download sapcar
  get_url:
    url: "{{ url_sapcar }}"
    dest: "{{ target_media_location }}/{{ sapcar }}"
    mode: 0755
    timeout: "{{ url_timeout }}"
  register: result
  until: result is succeeded
  retries: "{{ url_retries_cnt }}"
  delay: "{{ url_retries_delay }}"

- name: download HCMT 
  get_url:
    url: "{{ url_hcmt }}"
    dest: "{{ target_media_location }}/{{ hcmt }}"
    mode: 0750
    timeout: "{{ url_timeout }}"
  register: result
  until: result is succeeded
  retries: "{{ url_retries_cnt }}"
  delay: "{{ url_retries_delay }}"

- name: extract HCMT 
  command: "./{{ sapcar }} -manifest SIGNATURE.SMF -xvf {{ hcmt }}"
  args:
    chdir: "{{ target_media_location }}"
    creates: "{{ target_media_location }}/setup/hcmtsetup"

- name: Setup HCMT
  command: ./hcmtsetup
  args:
    chdir: "{{ target_media_location }}/setup"
    creates: "{{ target_media_location }}/setup/hcmt"

- name: Set Request to false to allow non-interactive run
  ansible.builtin.replace:
    path: "{{ target_media_location }}/setup/config/executionplan.json"
    regexp: '"Request": "true"'
    replace: '"Request": "false"'

- name: Lower Repeat Value to 1 to reduce long runtime
  ansible.builtin.replace:
    path: "{{ target_media_location }}/setup/config/executionplan.json"
    regexp: '"Value": "2"'
    replace: '"Value": "1"'

- name: run hcmt
  shell: ./hcmt -v -p config/executionplan.json
  args:
    chdir: "{{ target_media_location }}/setup"
    
