---

- name: create install dir
  file:
    path: {{ download_directory }}
    state: directory

- name: deploy hdblcm install template
  template:
    src: "{{ 'hdbserver_hana2.j2' }}"
    dest: "{{ download_directory }}/hdbserver_{{ sap_sid }}_install.cfg"

- name: deploy hdblcm password file
  template:
    src: "{{ 'hdbserver_passwords.j2' }}"
    dest: "{{ download_directory }}/hdbserver_{{ sap_sid }}_passwords.xml"

- name: Enter provided password into password file
  replace:
    path: "{{ download_directory }}/hdbserver_{{ sap_sid }}_passwords.xml"
    regexp: '\*\*\*'
    replace: "{{ pw_db_system }}"

- name: extract hdbserver
  command: "./{{ sapcar }} -manifest SIGNATURE.SMF -xvf {{ hdbserver }}"
  args:
    chdir: "{{ download_directory }}""
    creates: "{{ download_directory }}/SAP_HANA_DATABASE/hdblcm"

- name: run hdblcm
  shell: "pwd=$(<../hdbserver_{{ sap_sid }}_passwords.xml); rm ../hdbserver_{{ sap_sid }}_passwords.xml; echo $pwd | ./hdblcm --batch --action=install --configfile='../hdbserver_{{ sap_sid }}_install.cfg' --read_password_from_stdin=xml"
  args:
    chdir: "{{ download_directory }}/SAP_HANA_DATABASE"
