# Pipeline to deploy an Azure DevopsDeployment Agent

parameters:
- name: location
  displayName: Region
  type: string
  default: "eastus2euap"
  values:
  - "West Europe"
  - "North Europe"
  - "Germany West Central"
  - "eastus2euap"

- name: vmname
  displayName: DevOps Deployment Agent VM Name
  type: string
  default: "devopsagent"

- name: hostname
  displayName: DevOps Deployment Agent Hostname
  type: string
  default: "devopsagent"

- name: adminrg
  displayName: Resource group for the landing zone
  type: string
  default: "rg-devopsagent"

- name: vnetnameprefix
  displayName: VNET name prefix (location  will be added to the name and a 3 digit int.)
  type: string
  default: "vnet-sap-prod-"

- name: vnetrange
  displayName: VNET range
  type: string
  default: "10.10.0.0/16"

- name: sapsubnetnameprefix
  displayName: SAP subnet name prefix (location  will be added to the name and a 3 digit int.)
  type: string
  default: "sn-sap-prod-"

- name: sapsubnetrange
  displayName: SAP subnet range
  type: string
  default: "10.10.10.0/24"

- name: adminsubnetnameprefix
  displayName: Admin subnet name prefix (location  will be added to the name and a 3 digit int.)
  type: string
  default: "sn-sap-prod-"

- name: adminsubnetrange
  displayName: Admin subnet range
  type: string
  default: "10.10.10.0/24"

- name: subnet
  displayName: Target subnet
  type: string
  default: "snet-sap-prod-germanywestcentral-001"
  values:
  - "snet-sap-prod-westeurope-001"
  - "snet-sap-prod-germanywestcentral-001"
  - "sapprdsubnet"
  - "DEV-NOEU-SAP02_db-subnet"
  - "MIM-GEWC-SAP04_db-subnet"

- name: vnetrg
  displayName: VNET resource group
  type: string
  default: "SAPonAzureGermany"
  values:
  - "MIM-GEWC-SAP04-INFRASTRUCTURE"
  - "SAPonAzureWestEurope"
  - "SAPonAzureNorthEurope"
  - "SAPonAzureGermany"
  - "SAPonAzureFrance"
  - "SAPonAzureWestUS"

- name: winpw
  displayName: Windows user password
  type: string

- name: winpw
  displayName: Windows user password
  type: string

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  subnetid: /subscriptions/$(subscription)/resourceGroups/$(VNET_RG)/providers/Microsoft.Network/virtualNetworks/${{ parameters.vnet_subnet }}

steps:
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)'
        artifact: agent

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy an Agent'
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(azureconnectionname)'
        subscriptionId: '$(subscription)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: ${{ parameters.rg }}
        location: ${{ parameters.location }}
        templateLocation: 'URL of the file'
        csmFileLink: 'https://raw.githubusercontent.com/$(git_user)/sap-hana-vm/$(Build.SourceBranchName)/ARM-Template/devops-deployment-agent.json'
        overrideParameters: '-adminUsername "$(adminuser)" -adminPublicKey "$(sshkey)" -virtualMachineName "${{ parameters.vmname }}" -virtualMachineComputerName "${{ parameters.hostname }}" -subnetId "$(subnetid)" -Script_URL "$(url-agent-cfg)" -diagnosticsStorageAccountName "$(diagnosticsStorageAccountName)" '
        deploymentMode: 'Complete'
        deploymentName: 'devops-deployment-agent-$(Build.BuildId)'
        