# Pipeline to deploy an Azure DevopsDeployment Agent

parameters:
- name: location
  displayName: Region
  type: string
  default: "eastus2euap"
  values:
  - "West Europe"
  - "North Europe"
  - "Germany West Central"
  - "eastus2euap"

- name: mgmt-rg
  displayName: Resource group for the landing zone
  type: string
  default: "SAPonAzure(parameters.location)"

- name: deployervmname
  displayName: DevOps Deployment Agent VM Name
  type: string
  default: "devopsagent"

- name: deployerhostname
  displayName: DevOps Deployment Agent Hostname
  type: string
  default: "devopsagent"

- name: winvmname
  displayName: DevOps Deployment Agent VM Name
  type: string
  default: "devopsagent"

- name: winhostname
  displayName: DevOps Deployment Agent Hostname
  type: string
  default: "devopsagent"

- name: winpw
  displayName: Windows user password
  type: string

- name: vnetrange
  displayName: VNET range
  type: string
  default: "10.10.0.0/16"

- name: bastionsubnetrange
  displayName: Bastion subnet range
  type: string
  default: "10.10.2.0/24"

- name: adminsubnetrange
  displayName: Admin subnet range
  type: string
  default: "10.10.3.0/24"

- name: sapsubnetrange
  displayName: SAP subnet range
  type: string
  default: "10.10.10.0/24"

- name: rsvtype
  displayName: Recovery Service Vault Type
  type: string
  default: "LocallyRedundant"
  values:
  - "LocallyRedundant"
  - "ZoneRedundant"
  - "GeoRedundant"

- name: rsvtype
  displayName: Recovery Service Vault Type
  type: boolean
  default: False

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  subnetid: /subscriptions/$(subscription)/resourceGroups/$(VNET_RG)/providers/Microsoft.Network/virtualNetworks/${{ parameters.vnet_subnet }}

steps:
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)'
        artifact: agent

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy an Agent'
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(AZURE_CONNECTION_NAME)'
        subscriptionId: '$(ARM_SUBSCRIPTION_ID)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: ${{ parameters.adminrg }}
        location: ${{ parameters.location }}
        templateLocation: 'Linked artifact'
        csmFile: $(System.DefaultWorkingDirectory)/ARM-Template/sap-landing-zone.json
        overrideParameters: '-adminUsername "$(adminuser)" -adminPublicKey "$(sshkey)" -virtualMachineName "${{ parameters.vmname }}" -virtualMachineComputerName "${{ parameters.hostname }}" -subnetId "$(subnetid)" -Script_URL "$(url-agent-cfg)" -diagnosticsStorageAccountName "$(diagnosticsStorageAccountName)" '
        deploymentMode: 'Incremental'
        deploymentName: 'sap-landing-zone-$(Build.BuildId)'

