# Pipeline to deploy an Azure DevopsDeployment Agent

parameters:
- name: location
  displayName: Region
  type: string
  default: "East US 2 EUAP"
  values:
  - "West Europe"
  - "North Europe"
  - "France Central"
  - "Germany West Central"
  - "East US 2 EUAP"

- name: mgmtrg
  displayName: Resource group for landing zone resources
  type: string
  default: "SAPonAzureLocation"

- name: deployervmname
  displayName: DevOps Deployment Agent VM name prefix, location will be added (e.g. devopsagent-westeurope)
  type: string
  default: "devopsagent-"

- name: deployerhostname
  displayName: DevOps Deployment Agent hostname prefix, location will be added (e.g. devopsagent-westeurope)
  type: string
  default: "devopsagent-"

- name: winvmname
  displayName: Windows Admin VM name prefix
  type: string
  default: "winadmin-"

- name: winhostname
  displayName: Windows Admin hostname prefix
  type: string
  default: "winadmin-"

- name: vnetrange
  displayName: VNET range
  type: string
  default: "10.10.0.0/16"

- name: bastionsubnetrange
  displayName: Bastion subnet range
  type: string
  default: "10.10.2.0/24"

- name: adminsubnetrange
  displayName: Admin subnet range
  type: string
  default: "10.10.3.0/24"

- name: sapsubnetrange
  displayName: SAP subnet range
  type: string
  default: "10.10.10.0/24"

- name: rsvtype
  displayName: Recovery Service Vault Type
  type: string
  default: "LocallyRedundant"
  values:
  - "LocallyRedundant"
  - "ZoneRedundant"
  - "GeoRedundant"

- name: crr
  displayName: Recovery Service Vault Cross Region Restore enabled
  type: boolean
  default: False

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  - group: "SAP-deployments"
#  - name: resourcegroup
#    value: "${{ parameters.mgmtrg }}${{ parameters.location }}"

stages:
- stage: Publish_Pipeline_Artifact
  jobs:
  - job: Publish_Pipeline_Artifact
    workspace:
      clean: all
    steps:
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)'
        artifact: agent

- stage: Deploy the SAP landing zone
  jobs:
  - job: Deploy_the_SAP_landing_zone
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'Deploy the SAP landing zone'
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: '$(AZURE_CONNECTION_NAME)'
          subscriptionId: '$(ARM_SUBSCRIPTION_ID)'
          action: 'Create Or Update Resource Group'
          resourceGroupName: '${{ parameters.mgmtrg }}'
          location: '${{ parameters.location }}'
          templateLocation: 'Linked artifact'
          csmFile: $(System.DefaultWorkingDirectory)/ARM-Template/sap-landing-zone.json
          overrideParameters: '-adminUsername "$(adminuser)" -adminPublicKey "$(sshkey)" -WindowsPassword "$(winpw)" -DevOpsDeployerVMName "${{ parameters.deployervmname }}" -DevOpsDeployerComputerName "${{ parameters.deployerhostname }}"  -SAPWinAdminVMName "${{ parameters.winvmname }}" -SAPWinAdminComputerName "${{ parameters.winhostname }}" -SAPVNETNameAddressSpace "["${{ parameters.vnetrange }}"]" -SAPAdminSubnetAddressRange "${{ parameters.adminsubnetrange }}" -SAPSubnetAddressRange "${{ parameters.sapsubnetrange }}" -BastianSubnetAddressRange "${{ parameters.bastionsubnetrange }}" -VaultStorageType "${{ parameters.rsvtype }}" '
          deploymentMode: 'Incremental'
          deploymentName: 'sap-landing-zone-$(Build.BuildId)'
