---

- name: Install Module Module Az
  command: pwsh -Command Install-Module Posh-SSH -Force

- name: Install Module Az.NetAppFiles
  command: pwsh -Command Install-Module Az.NetAppFiles -Force

- name: Install Module Posh-SSH
  command: pwsh -Command Install-Module Posh-SSH -Force

- name: Run the quality check
  command: pwsh -Command "Scripts/QualityCheck.ps1 -VMOperatingSystem SUSE -VMDatabase HANA -VMRole DB -AzVMResourceGroup {{ rg }} -AzVMName {{ vmname }} -VMHostname {{ ip }} -VMUsername {{ adminuser }} -SSHKey ~/.ssh/id_rsa "

- name: Copy quality check result HTML file to Inventory 
  ansible.builtin.copy:
    src: "Scripts/{{ vmname }}*.html"
    dest: "{{ inventorypath }}/"