---

- name: Install Module Module Az
  ansible.builtin.shell: |
    if (Get-Module -ListAvailable -Name Az) {
        Write-Host "Module Az exists"
    }
    else {
        Write-Host "Module does not exist"
        Install-Module Az -Force
    }
  args:
    executable: pwsh

- name: Install Module Az.NetAppFiles
  ansible.builtin.shell: |
    if (Get-Module -ListAvailable -Name Az.NetAppFiles) {
        Write-Host "Module Az.NetAppFiles exists"
    }
    else {
        Write-Host "Module Az.NetAppFiles does not exist"
        Install-Module Az.NetAppFiles -Force
    }
  args:
    executable: pwsh

- name: Install Module Posh-SSH
  ansible.builtin.shell: |
    if (Get-Module -ListAvailable -Name Posh-SSH) {
        Write-Host "Module Posh-SSH exists"
    }
    else {
        Write-Host "Module Posh-SSH does not exist"
        Install-Module Posh-SSH -Force
    }
  args:
    executable: pwsh

- name: Run the quality check
  command: pwsh -Command ".\QualityCheck.ps1 -VMOperatingSystem SUSE -VMDatabase HANA -VMRole DB -AzVMResourceGroup {{ rg }} -AzVMName {{ vmname }} -VMHostname {{ ip }} -VMUsername {{ adminuser }} -SSHKey ~/.ssh/id_rsa "
  args:
    chdir: "{{ workdir }}/Scripts/"

- name: Copy quality check result HTML file to Inventory 
  ansible.builtin.copy:
    src:  "{{ workdir }}/Scripts/{{ vmname }}*.html"
    dest: "{{ inventory }}/{{ rg }}/"