---

- name: Install Module Module Az
  command: pwsh -Command Install-Module Posh-SSH -Force

- name: Install Module Az.NetAppFiles
  command: pwsh -Command Install-Module Az.NetAppFiles -Force

- name: Install Module Posh-SSH
  command: pwsh -Command Install-Module Posh-SSH -Force

